apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-sonar
  labels:
    app: postgres-sonar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-sonar
  template:
    metadata:
      name: postgres-sonar
      labels:
        app: postgres-sonar
    spec:
      containers:
      - name: postgres-sonar
        image: postgres:16
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-sonar-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-sonar-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-sonar-secret
              key: POSTGRES_DB
        volumeMounts:
        - name: postgres-sonar-mount
          mountPath: /var/lib/postgresql/data/
  volumeClaimTemplates:
  - metadata:
      name: postgres-sonar-mount
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-sonar-service
  labels:
    app: postgres-sonar
spec:
  selector:
    app: postgres-sonar
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
